/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
ProjectxAudioProcessor::ProjectxAudioProcessor()
{
}

ProjectxAudioProcessor::~ProjectxAudioProcessor()
{
}

//==============================================================================
const String ProjectxAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

int ProjectxAudioProcessor::getNumParameters()
{
    return 0;
}

float ProjectxAudioProcessor::getParameter (int index)
{
    return 0.0f;
}

void ProjectxAudioProcessor::setParameter (int index, float newValue)
{
}

const String ProjectxAudioProcessor::getParameterName (int index)
{
    return String();
}

const String ProjectxAudioProcessor::getParameterText (int index)
{
    return String();
}

const String ProjectxAudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String ProjectxAudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool ProjectxAudioProcessor::isInputChannelStereoPair (int index) const
{
    return true;
}

bool ProjectxAudioProcessor::isOutputChannelStereoPair (int index) const
{
    return true;
}

bool ProjectxAudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool ProjectxAudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool ProjectxAudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double ProjectxAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int ProjectxAudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int ProjectxAudioProcessor::getCurrentProgram()
{
    return 0;
}

void ProjectxAudioProcessor::setCurrentProgram (int index)
{
}

const String ProjectxAudioProcessor::getProgramName (int index)
{
    return String();
}

void ProjectxAudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void ProjectxAudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
}

void ProjectxAudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void ProjectxAudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    buffer.clear();
     
    MidiBuffer processedMidi;
    int time;
    MidiMessage m;
 
    for (MidiBuffer::Iterator i (midiMessages); i.getNextEvent (m, time);)
    {
        if (m.isNoteOn())
        {
            uint8 newVel = (uint8)noteOnVel;
            m = MidiMessage::noteOn(m.getChannel(), m.getNoteNumber(), newVel);
        }
        else if (m.isNoteOff())
        {
        }
        else if (m.isAftertouch())
        {
        }
        else if (m.isPitchWheel())
        {
        }
 
        processedMidi.addEvent (m, time);
    }
 
    midiMessages.swapWith (processedMidi);
}

//==============================================================================
bool ProjectxAudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* ProjectxAudioProcessor::createEditor()
{
    return new ProjectxAudioProcessorEditor (*this);
}

//==============================================================================
void ProjectxAudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void ProjectxAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new ProjectxAudioProcessor();
}
